services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json:ro
      - ./vite.config.js:/app/vite.config.js:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      - ./resources:/app/resources:ro
      - ./stubs:/app/stubs
      - node_modules:/app/node_modules

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json:ro
      - ./vite.config.js:/app/vite.config.js:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      - ./resources:/app/resources:ro
      - ./stubs:/app/stubs
      - node_modules:/app/node_modules
    command: npm run build:watch
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Установка зависимостей: docker-compose run --rm npm install axios
  npm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules:/app/node_modules
    entrypoint: npm

volumes:
  node_modules:
